### ISSUE TITLE
🏝️ Feature Request: Can you add an infinite or get like 2 million coins hack so you have a lot of coins, or make a hack that lets you actually keep all of the blooks in the game

### ISSUE THREAD

**Issue by swampdonkey1** [Blooket-Cheats/Blooket-Hacks#110]
### Contact Details

29abernethykage@canyonstudent.net

### Gamemode

Just the normal ike screen when you load into blooket

### Requested function

That I have infinite coins

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by swampdonkey1** [comment]
Please someone figure this out!!!!!!!!!!!!!!!!!!!!!

**Comment by CrazyH2** [comment]
Not possible this is server-side not client-side

**Comment by CrazyH2** [comment]
Please read before creating an issue!

Over the last few months, we have gotten a significant number of issues asking us to “max out” accounts, “give infinite tokens”, “bypass token limit” or “give all the blooks”. Ask any hack creator! They will also say it is impossible to do this if they know what they are doing. This is because your account data is server-side, and if you do not know what that means, then please don’t create an issue asking us to do something similar.

Also, we have gotten some issues where people obviously haven’t checked to see if that hack or issue already exists, like “infinite crypto”. There is a reason why you have eyes or a screen reader!
