### ISSUE TITLE
🪲 Bug: Add bookmarklet

### ISSUE THREAD

**Issue by RandyPlayzMC** [Blooket-Cheats/Blooket-Hacks#8]
### Contact Details

shirandy72@gmail.com

### Hacks used

Spam Boxes and Add Rewards

### What happened?

Nothing happened.

### What browsers are you seeing the problem on?

Chromium based

### Relevant console errors

```JavaScript
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cph101** [comment]
Sorry, @RandyPlayzMC, but I’m going to close this because you’re issue doesn’t make sense. If you’re requesting a bookmarklet version of these hacks:
1. Please use Feature Request instead
2. The hacks you mentioned already exist
If you need anything else, please create a new issue with more specific details. Thank you for your understanding.
